import Phaser from 'phaser';

interface ManifestJson {
  coverage?: Record<
    string,
    { exported: number; symbols: number; frames: number; pct: number }
  >;
}

const CENTER = 380;

/**
 * M0 proof scene: renders sprites from the pipeline-generated atlas and
 * self-verifies the dev proxy and coverage report on screen.
 *
 * Atlas contract: docs/04-asset-pipeline.md. Keys look like
 * `ingredient_asset/apple/idle`. Generated by `npm run pipeline`.
 */
export class BootScene extends Phaser.Scene {
  private loadErrors: string[] = [];

  constructor() {
    super('Boot');
  }

  preload(): void {
    // Multi-atlas JSON (textures array) MUST use the multiatlas loader —
    // load.atlas would treat this URL as a texture image (Phaser docs).
    this.load.on(Phaser.Loader.Events.FILE_LOAD_ERROR, (file: unknown) => {
      const f = file as { key?: string; url?: string };
      this.loadErrors.push(`${f.key ?? '?'} (${f.url ?? '?'})`);
    });
    this.load.multiatlas(
      'ingredient',
      'assets/generated/atlases/ingredient_asset.json',
    );
  }

  create(): void {
    this.add
      .text(CENTER, 60, 'Restaurant City HTML5', {
        fontFamily: 'Arial, sans-serif',
        fontSize: '28px',
        color: '#ffffff',
      })
      .setOrigin(0.5);
    this.add
      .text(CENTER, 92, 'M0 — asset pipeline proof (ingredient_asset.swf)', {
        fontFamily: 'Arial, sans-serif',
        fontSize: '14px',
        color: '#9fd8e8',
      })
      .setOrigin(0.5);

    this.probeProxy();
    this.showCoverage();
    this.showLoadErrors();
    try {
      this.showSprites();
    } catch (err) {
      this.add
        .text(CENTER, 540, `scene error: ${String(err)}`, {
          fontFamily: 'monospace',
          fontSize: '11px',
          color: '#ff8a80',
          wordWrap: { width: 700 },
        })
        .setOrigin(0.5);
    }
  }

  /** Prints loader failures on screen so a half-loaded scene explains itself. */
  private showLoadErrors(): void {
    if (this.loadErrors.length === 0) return;
    this.add
      .text(
        CENTER,
        560,
        `LOAD ERRORS: ${this.loadErrors.join(' | ')}`,
        {
          fontFamily: 'monospace',
          fontSize: '11px',
          color: '#ff8a80',
          wordWrap: { width: 720 },
        },
      )
      .setOrigin(0.5);
  }

  /** M0 acceptance: the dev proxy can fetch /bin-xml/ingredient.bin via :5173. */
  private probeProxy(): void {
    const style = { fontFamily: 'monospace', fontSize: '13px', color: '#c8c8c8' };
    fetch('/bin-xml/ingredient.bin')
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        const buf = await r.arrayBuffer();
        return {
          text: `proxy OK: /bin-xml/ingredient.bin -> ${buf.byteLength} bytes`,
          color: '#7ddb8a',
        };
      })
      .catch((err: unknown) => ({
        text: `proxy FAILED: ${err instanceof Error ? err.message : String(err)}`,
        color: '#ff8a80',
      }))
      .then(({ text, color }) =>
        this.add.text(CENTER, 130, text, { ...style, color }).setOrigin(0.5),
      );
  }

  /** Shows the pipeline coverage report from the generated manifest. */
  private showCoverage(): void {
    const style = { fontFamily: 'monospace', fontSize: '13px', color: '#c8c8c8' };
    fetch('/assets/generated/manifest.json')
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return (await r.json()) as ManifestJson;
      })
      .then((m) => {
        const c = m.coverage?.['ingredient_asset'];
        if (!c) throw new Error('no ingredient_asset coverage');
        return {
          text: `pipeline coverage: ${c.exported}/${c.symbols} symbols (${c.pct}%), ${c.frames} frames`,
          color: c.pct >= 100 ? '#7ddb8a' : '#ffb74d',
        };
      })
      .catch((err: unknown) => ({
        text: `manifest FAILED: ${err instanceof Error ? err.message : String(err)}`,
        color: '#ff8a80',
      }))
      .then(({ text, color }) =>
        this.add.text(CENTER, 158, text, { ...style, color }).setOrigin(0.5),
      );
  }

  /** Renders one animated timeline sprite plus a static row of icons. */
  private showSprites(): void {
    const texture = this.textures.get('ingredient');
    if (!texture) {
      throw new Error("texture 'ingredient' missing — atlas failed to load");
    }
    const frames = texture.getFrameNames();
    const symbols = [...new Set(frames.map((k) => k.replace(/\/[^/]+$/, '')))].sort();

    let anim: { symbol: string; idle: string; grey: string } | undefined;
    for (const symbol of symbols) {
      const idle = frames.find((k) => k === `${symbol}/idle`);
      const grey = frames.find((k) => k === `${symbol}/grey`);
      if (idle && grey) {
        anim = { symbol, idle, grey };
        break;
      }
    }

    if (anim) {
      this.anims.create({
        key: 'm0-toggle',
        frames: [{ key: anim.idle }, { key: anim.grey }],
        frameRate: 2,
        repeat: -1,
      });
      this.add
        .sprite(CENTER, 320, 'ingredient', anim.idle)
        .setScale(2)
        .play('m0-toggle');
      this.add
        .text(CENTER, 396, `animated timeline: ${anim.idle} <-> ${anim.grey}`, {
          fontFamily: 'monospace',
          fontSize: '12px',
          color: '#9fd8e8',
        })
        .setOrigin(0.5);
    } else {
      // Diagnostics instead of a bare message: shows exactly what loaded.
      const sample = frames.slice(0, 5).join(', ');
      this.add
        .text(CENTER, 320, `no two-frame (idle/grey) symbol found in atlas`, {
          fontFamily: 'monospace',
          fontSize: '13px',
          color: '#ff8a80',
        })
        .setOrigin(0.5);
      this.add
        .text(
          CENTER,
          348,
          `loaded ${frames.length} frames, ${symbols.length} symbols; sample keys: ${sample || '(none)'}`,
          {
            fontFamily: 'monospace',
            fontSize: '11px',
            color: '#c8c8c8',
            wordWrap: { width: 700 },
          },
        )
        .setOrigin(0.5);
    }

    const row = symbols.filter((s) => s !== anim?.symbol).slice(0, 8);
    const x0 = CENTER - ((row.length - 1) * 64) / 2;
    row.forEach((symbol, i) => {
      const key = frames.find((k) => k.startsWith(`${symbol}/`));
      if (key) {
        this.add.sprite(x0 + i * 64, 480, 'ingredient', key);
      }
    });
  }
}
