import Phaser from 'phaser';
import { RpcClient } from '../../net/rpc-client';
import { fetchSession } from '../../net/session';

interface CoverageEntry {
  symbols: number;
  exported: number;
  frames: number;
  pct: number;
  pages?: number;
}

interface ManifestJson {
  atlases?: { id: string; pages?: number }[];
  audio?: { id: string; file: string; kind: string }[];
  data?: { id: string; file: string }[];
  langs?: { code: string; file: string }[];
  coverage?: Record<string, CoverageEntry>;
}

const CENTER = 380;
// Manifest data/audio/lang `file` fields are relative to
// public/assets/generated/ (contract: docs/04-asset-pipeline.md).
const GENERATED = 'assets/generated/';

/**
 * M0/M1 proof scene: renders sprites from the pipeline-generated atlas,
 * shows pipeline coverage for every asset SWF, and self-verifies the dev
 * proxy, data files, and an exported audio track on screen.
 *
 * Atlas contract: docs/04-asset-pipeline.md. Generated by `npm run pipeline`.
 */
export class ProofScene extends Phaser.Scene {
  private loadErrors: string[] = [];

  private audioCtx: AudioContext | null = null;
  private audioBuffer: AudioBuffer | null = null;
  private audioStatus: Phaser.GameObjects.Text | null = null;
  private firstSfx: string | null = null;

  constructor() {
    super('proof');
  }

  preload(): void {
    // Multi-atlas JSON (textures array) MUST use the multiatlas loader —
    // load.atlas would treat this URL as a texture image (Phaser docs).
    this.load.on(Phaser.Loader.Events.FILE_LOAD_ERROR, (file: unknown) => {
      const f = file as { key?: string; url?: string };
      this.loadErrors.push(`${f.key ?? '?'} (${f.url ?? '?'})`);
    });
    this.load.multiatlas(
      'ingredient',
      'assets/generated/atlases/ingredient_asset.json',
    );
  }

  create(): void {
    this.add
      .text(CENTER, 52, 'Restaurant City HTML5', {
        fontFamily: 'Arial, sans-serif',
        fontSize: '26px',
        color: '#ffffff',
      })
      .setOrigin(0.5);
    this.add
      .text(CENTER, 80, 'M1 — asset pipeline complete (7 SWFs, data, audio)', {
        fontFamily: 'Arial, sans-serif',
        fontSize: '14px',
        color: '#9fd8e8',
      })
      .setOrigin(0.5);

    this.probeProxy();
    this.showManifestStats();
    this.probeSession();
    this.showLoadErrors();
    try {
      this.showSprites();
    } catch (err) {
      this.add
        .text(CENTER, 570, `scene error: ${String(err)}`, {
          fontFamily: 'monospace',
          fontSize: '11px',
          color: '#ff8a80',
          wordWrap: { width: 700 },
        })
        .setOrigin(0.5);
    }
  }

  /** M0 acceptance: the dev proxy can fetch /bin-xml/ingredient.bin via :5173. */
  private probeProxy(): void {
    const style = { fontFamily: 'monospace', fontSize: '12px', color: '#c8c8c8' };
    fetch('/bin-xml/ingredient.bin')
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        const buf = await r.arrayBuffer();
        return {
          text: `proxy OK: /bin-xml/ingredient.bin -> ${buf.byteLength} bytes`,
          color: '#7ddb8a',
        };
      })
      .catch((err: unknown) => ({
        text: `proxy FAILED: ${err instanceof Error ? err.message : String(err)}`,
        color: '#ff8a80',
      }))
      .then(({ text, color }) =>
        this.add.text(CENTER, 112, text, { ...style, color }).setOrigin(0.5),
      );
  }

  /** Shows manifest totals: coverage per SWF, data files, langs, audio. */
  private showManifestStats(): void {
    const style = { fontFamily: 'monospace', fontSize: '12px', color: '#c8c8c8' };
    fetch('/assets/generated/manifest.json')
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return (await r.json()) as ManifestJson;
      })
      .then((m) => {
        const cov = Object.entries(m.coverage ?? {});
        const worst = cov.reduce<CoverageEntry | null>(
          (acc, [, c]) => (acc === null || c.pct < acc.pct ? c : acc),
          null,
        );
        const lines: { text: string; color: string }[] = [];
        lines.push({
          text: `coverage: ${cov.length} SWFs, worst ${worst?.pct ?? '?'}% — ` +
            cov.map(([n, c]) => `${n.split('_')[0]}:${c.pct}`).join(' '),
          color: (worst?.pct ?? 0) >= 100 ? '#7ddb8a' : '#ffb74d',
        });
        lines.push({
          text: `data: ${m.data?.length ?? 0} datasets, ${m.langs?.length ?? 0} langs, ` +
            `${m.audio?.length ?? 0} audio tracks`,
          color: '#c8c8c8',
        });
        const sfx = m.audio?.find((a) => a.kind === 'sfx');
        if (sfx) {
          this.firstSfx = sfx.file;
          lines.push({
            text: `audio proof: click anywhere to decode+play ${sfx.id}`,
            color: '#9fd8e8',
          });
        }
        lines.forEach((l, i) =>
          this.add.text(CENTER, 140 + i * 22, l.text, { ...style, color: l.color }).setOrigin(0.5),
        );
        if (this.firstSfx) {
          this.input.on('pointerdown', () => void this.playFirstSfx());
        }
      })
      .catch((err: unknown) => {
        this.add
          .text(CENTER, 140, `manifest FAILED: ${err instanceof Error ? err.message : String(err)}`, {
            ...style,
            color: '#ff8a80',
          })
          .setOrigin(0.5);
      });
  }

  /** Decodes and plays the first SFX through Web Audio (M1 audio proof). */
  private async playFirstSfx(): Promise<void> {
    if (!this.firstSfx || this.audioStatus?.text.includes('playing')) return;
    try {
      this.audioCtx ??= new AudioContext();
      if (!this.audioBuffer) {
        const url = `/${GENERATED}${this.firstSfx}`;
        const r = await fetch(url);
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        // Vite's SPA fallback answers unknown paths with 200 text/html —
        // guard the content type so a misrouted URL fails loudly instead of
        // surfacing as a confusing decode error.
        const type = r.headers.get('content-type') ?? '';
        if (!type.includes('audio')) {
          throw new Error(`unexpected content-type "${type}" for ${url}`);
        }
        this.audioBuffer = await this.audioCtx.decodeAudioData(await r.arrayBuffer());
      }
      await this.audioCtx.resume();
      const src = this.audioCtx.createBufferSource();
      src.buffer = this.audioBuffer;
      src.connect(this.audioCtx.destination);
      src.start();
      this.setAudioStatus(`audio OK: played ${this.firstSfx}`, '#7ddb8a');
    } catch (err) {
      this.setAudioStatus(
        `audio FAILED: ${err instanceof Error ? err.message : String(err)}`,
        '#ff8a80',
      );
    }
  }

  private setAudioStatus(text: string, color: string): void {
    if (this.audioStatus) {
      this.audioStatus.setText(text).setColor(color);
    } else {
      this.audioStatus = this.add
        .text(CENTER, 480, text, {
          fontFamily: 'monospace',
          fontSize: '12px',
          color,
        })
        .setOrigin(0.5);
    }
  }

  /** M2 proof: session state + RPC handshake against the local backend. */
  private probeSession(): void {
    const style = { fontFamily: 'monospace', fontSize: '12px', color: '#c8c8c8' };
    void fetchSession()
      .then(async (session) => {
        if (!session.loggedIn) {
          const link = this.add
            .text(CENTER, 220, 'not logged in — click here to log in', {
              ...style,
              color: '#ffb74d',
              backgroundColor: '#00000000',
            })
            .setOrigin(0.5)
            .setInteractive({ useHandCursor: true });
          link.on('pointerdown', () => {
            window.location.assign('/login?next=/');
          });
          return;
        }
        const client = new RpcClient();
        const serverTime = await client.handshake();
        this.add
          .text(
            CENTER,
            220,
            `session OK: ${session.account?.username ?? '?'} — handshake done, server time ${serverTime}`,
            { ...style, color: '#7ddb8a' },
          )
          .setOrigin(0.5);
      })
      .catch((err: unknown) => {
        this.add
          .text(CENTER, 220, `session FAILED: ${err instanceof Error ? err.message : String(err)}`, {
            ...style,
            color: '#ff8a80',
            wordWrap: { width: 700 },
          })
          .setOrigin(0.5);
      });
  }

  /** Prints loader failures on screen so a half-loaded scene explains itself. */
  private showLoadErrors(): void {
    if (this.loadErrors.length === 0) return;
    this.add
      .text(CENTER, 545, `LOAD ERRORS: ${this.loadErrors.join(' | ')}`, {
        fontFamily: 'monospace',
        fontSize: '11px',
        color: '#ff8a80',
        wordWrap: { width: 720 },
      })
      .setOrigin(0.5);
  }

  /** Renders one animated timeline sprite plus a static row of icons. */
  private showSprites(): void {
    const texture = this.textures.get('ingredient');
    if (!texture) {
      throw new Error("texture 'ingredient' missing — atlas failed to load");
    }
    const frames = texture.getFrameNames();
    const symbols = [...new Set(frames.map((k) => k.replace(/\/[^/]+$/, '')))].sort();

    let anim: { symbol: string; idle: string; grey: string } | undefined;
    for (const symbol of symbols) {
      const idle = frames.find((k) => k === `${symbol}/idle`);
      const grey = frames.find((k) => k === `${symbol}/grey`);
      if (idle && grey) {
        anim = { symbol, idle, grey };
        break;
      }
    }

    if (anim) {
      // Phaser animation frames use { key: <textureKey>, frame: <frameName> } —
      // a bare { key } is treated as a TEXTURE key, not a frame name.
      this.anims.create({
        key: 'm0-toggle',
        frames: [
          { key: 'ingredient', frame: anim.idle },
          { key: 'ingredient', frame: anim.grey },
        ],
        frameRate: 2,
        repeat: -1,
      });
      this.add
        .sprite(CENTER, 290, 'ingredient', anim.idle)
        .setScale(2)
        .play('m0-toggle');
      this.add
        .text(CENTER, 355, `animated timeline: ${anim.idle} <-> ${anim.grey}`, {
          fontFamily: 'monospace',
          fontSize: '11px',
          color: '#9fd8e8',
        })
        .setOrigin(0.5);
    } else {
      const sample = frames.slice(0, 5).join(', ');
      this.add
        .text(CENTER, 290, 'no two-frame (idle/grey) symbol found in atlas', {
          fontFamily: 'monospace',
          fontSize: '12px',
          color: '#ff8a80',
        })
        .setOrigin(0.5);
      this.add
        .text(
          CENTER,
          316,
          `loaded ${frames.length} frames, ${symbols.length} symbols; sample keys: ${sample || '(none)'}`,
          {
            fontFamily: 'monospace',
            fontSize: '10px',
            color: '#c8c8c8',
            wordWrap: { width: 700 },
          },
        )
        .setOrigin(0.5);
    }

    const row = symbols.filter((s) => s !== anim?.symbol).slice(0, 8);
    const x0 = CENTER - ((row.length - 1) * 64) / 2;
    row.forEach((symbol, i) => {
      const key = frames.find((k) => k.startsWith(`${symbol}/`));
      if (key) {
        this.add.sprite(x0 + i * 64, 405, 'ingredient', key);
      }
    });
  }
}

